### ISSUE TITLE
nodemailer 

### ISSUE THREAD

**Issue by a-bellec** [abellec29/webarmature#1]
Works in local
Not in production mode
Contact (client/components/navbar/navbar.html) code has been commented

**Comment by a-bellec** [comment]
works with "send-email-test.js" --> node send-email-test.js
On navbar no reaction when button "send" is pressed

**Comment by Thuranel** [comment]
This problem is most likely caused by the fact that the message that are sent are not sent by a verified account (through a service like gmail). Because the account that the message comes from is not deemed "correct" the server firewall blocks the email on reception. Unfortunately, node only tell us if our message is sent, not if it was received correctly which explains why there is no error. Also, I just checked the signUp email doesn't seem to work either.

We probably need to set up nodemailer through a mail service to correct the issue. Any mail service should work. There is also the possibility that we can simply whitelist the IP from which the mail is sent so the server doesn't stop it anymore.

I'm not sure that what I guessed is totally right, but it should be possible to check it by looking through the server logs.
